
export const CHECK_SECURITY_SUCCESS = 'CHECK_SECURITY_SUCCESS';

export const LOGIN_REQUEST = 'LOGIN_REQUEST';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';

export const CHECK_SERVER_SUCCESS = 'CHECK_SERVER_SUCCESS';