export const ZINDEX = {
    DRAWER_INTERACTABLE: 1,
    TAB_DISCOVERY_TOOLBAR: 10,
    TAB_DISCOVERY_FLOAT_BUTTON: 10,
    TAB_DISCOVERY_CONTENT_BODY: 9,
    TAB_DISCOVERY_OVERLAY_LOADING: 11,
    TAB_DISCOVERY_CONTENT_LIST: 10,
    TAB_DISCOVERY_OVERLAY_DRAWER_OPENED: 12,
    LOCATION_LOADING: 11,
    TAB_BOOKING_CONTENT_BODY: 9,
    TAB_BOOKING_OVERLAY_LOADING: 11,
    TAB_BOOKING_CONTENT_LIST: 10,
    TAB_BOOKING_OVERLAY_DRAWER_OPENED: 12,
    SHAKE_PROGRESS_VIEW: 1,
    SHAKE_PROGRESS_OVERLAY: 0,
    POPOVER_CHANGE_DATE_BOOKING: 21,
    POPUP_BANNER_300x400: 22
}
