# Uncomment the next line to define a global platform for your project
platform :ios, '9.0'

target 'testFastImage' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for testFastImage

  target 'testFastImage-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
    pod 'react-native-fast-image', :path => '../node_modules/react-native-fast-image'

  end

  target 'testFastImageTests' do
    inherit! :search_paths
    # Pods for testing
  end

end

target 'testFastImage-tvOS' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for testFastImage-tvOS


end
