

import React from 'react';
import {Dimensions} from 'react-native';

export const url = 'https://cms.aladin.pea.vn'
export const screen = Dimensions.get('window');
export const Color = '#c41a36';
export const ClTxtGrey = '#5d5d5d';
export const countries = [
  {
    name: 'Việt Nam',
    id: 'VN',
    icon: require('../icons/countries/VN.png'),
  },
  {
    name: 'Mỹ',
    id: 'US',
    icon: require('../icons/countries/US.png'),
  },
  {
    name: 'Trung Quốc',
    id: 'CN',
    icon: require('../icons/countries/CN.png'),
  },
  {
    name: 'Nhật Bản',
    id: 'JP',
    icon: require('../icons/countries/JP.png'),
  },
  {
    name: 'Canada',
    id: 'CA',
    icon: require('../icons/countries/CA.png'),
  },
  {
    name: 'Australia',
    id: 'AT',
    icon: require('../icons/countries/AT.png'),
  },
  {
    name: 'Afghanistan',
    id: 'AF',
    icon: require('../icons/countries/AF.png'),
  },
  {
    name: 'Bahrain',
    id: 'BH',
    icon: require('../icons/countries/BH.png'),
  },
  {
    name: 'Azerbaijan',
    id: 'AZ',
    icon: require('../icons/countries/AZ.png'),
  },
  
  // {
  //   name: 'Thái Lan',
  //   value: 'TH',
  //   icon: require('../icons/ic_mobile.png'),
  // },
  // {
  //   name: 'Trung Quốc',
  //   value: 'CN',
  //   icon: require('../icons/ic_mobile.png'),
  // },
  // {
  //   name: 'Nhật Bản',
  //   value: 'JP',
  //   icon: require('../icons/ic_mobile.png'),
  // }
];

export const profiles = [
  {
    title: 'Thông tin cá nhân',
    icon: require('../icons/ic_user.png'),
    type: 0,
  },
  {
    title: 'Địa chỉ giao hàng',
    icon: require('../icons/ic_location.png'),
    type: 1,
  },
  {
    title: 'Liên hệ hợp tác',
    icon: require('../icons/ic_contact.png'),
    type: 9,
  },
  {
    title: 'Đơn hàng của tôi',
    icon: require('../icons/ic_list.png'),
    type: 2,
  },
  {
    title: 'Hướng dẫn mua hàng',
    icon: require('../icons/ic_guide.png'),
    type: 3,
  },
  {
    title: 'Hướng dẫn bán hàng',
    icon: require('../icons/ic_guide.png'),
    type: 4,
  },
  {
    title: 'Hướng dẫn rút tiền lãi bán hàng',
    icon: require('../icons/ic_guide.png'),
    type: 5,
  },
  {
    title: 'Chính sách',
    icon: require('../icons/ic_primary.png'),
    type: 6,
  },
  {
    title: 'Trợ giúp',
    icon: require('../icons/ic_help.png'),
    type: 7,
  },
  {
    title: 'Đăng xuất',
    icon: require('../icons/ic_logout.png'),
    type: 8,
  },
]

export const Entities = {
  "'": "&apos;",
  "<": "&lt;",
  ">": "&gt;",
  " ": "&nbsp;",
  "¡": "&iexcl;",
  "¢": "&cent;",
  "£": "&pound;",
  "¤": "&curren;",
  "¥": "&yen;",
  "¦": "&brvbar;",
  "§": "&sect;",
  "¨": "&uml;",
  "©": "&copy;",
  "ª": "&ordf;",
  "«": "&laquo;",
  "¬": "&not;",
  "®": "&reg;",
  "¯": "&macr;",
  "°": "&deg;",
  "±": "&plusmn;",
  "²": "&sup2;",
  "³": "&sup3;",
  "´": "&acute;",
  "µ": "&micro;",
  "¶": "&para;",
  "·": "&middot;",
  "¸": "&cedil;",
  "¹": "&sup1;",
  "º": "&ordm;",
  "»": "&raquo;",
  "¼": "&frac14;",
  "½": "&frac12;",
  "¾": "&frac34;",
  "¿": "&iquest;",
  "À": "&Agrave;",
  "Á": "&Aacute;",
  "Â": "&Acirc;",
  "Ã": "&Atilde;",
  "Ä": "&Auml;",
  "Å": "&Aring;",
  "Æ": "&AElig;",
  "Ç": "&Ccedil;",
  "È": "&Egrave;",
  "É": "&Eacute;",
  "Ê": "&Ecirc;",
  "Ë": "&Euml;",
  "Ì": "&Igrave;",
  "Í": "&Iacute;",
  "Î": "&Icirc;",
  "Ï": "&Iuml;",
  "Ð": "&ETH;",
  "Ñ": "&Ntilde;",
  "Ò": "&Ograve;",
  "Ó": "&Oacute;",
  "Ô": "&Ocirc;",
  "Õ": "&Otilde;",
  "Ö": "&Ouml;",
  "×": "&times;",
  "Ø": "&Oslash;",
  "Ù": "&Ugrave;",
  "Ú": "&Uacute;",
  "Û": "&Ucirc;",
  "Ü": "&Uuml;",
  "Ý": "&Yacute;",
  "Þ": "&THORN;",
  "ß": "&szlig;",
  "à": "&agrave;",
  "á": "&aacute;",
  "â": "&acirc;",
  "ã": "&atilde;",
  "ä": "&auml;",
  "å": "&aring;",
  "æ": "&aelig;",
  "ç": "&ccedil;",
  "è": "&egrave;",
  "é": "&eacute;",
  "ê": "&ecirc;",
  "ë": "&euml;",
  "ì": "&igrave;",
  "í": "&iacute;",
  "î": "&icirc;",
  "ï": "&iuml;",
  "ð": "&eth;",
  "ñ": "&ntilde;",
  "ò": "&ograve;",
  "ó": "&oacute;",
  "ô": "&ocirc;",
  "õ": "&otilde;",
  "ö": "&ouml;",
  "÷": "&divide;",
  "ø": "&oslash;",
  "ù": "&ugrave;",
  "ú": "&uacute;",
  "û": "&ucirc;",
  "ü": "&uuml;",
  "ý": "&yacute;",
  "þ": "&thorn;",
  "ÿ": "&yuml;",
  "Œ": "&OElig;",
  "œ": "&oelig;",
  "Š": "&Scaron;",
  "š": "&scaron;",
  "Ÿ": "&Yuml;",
  "ƒ": "&fnof;",
  "ˆ": "&circ;",
  "˜": "&tilde;",
  "Α": "&Alpha;",
  "Β": "&Beta;",
  "Γ": "&Gamma;",
  "Δ": "&Delta;",
  "Ε": "&Epsilon;",
  "Ζ": "&Zeta;",
  "Η": "&Eta;",
  "Θ": "&Theta;",
  "Ι": "&Iota;",
  "Κ": "&Kappa;",
  "Λ": "&Lambda;",
  "Μ": "&Mu;",
  "Ν": "&Nu;",
  "Ξ": "&Xi;",
  "Ο": "&Omicron;",
  "Π": "&Pi;",
  "Ρ": "&Rho;",
  "Σ": "&Sigma;",
  "Τ": "&Tau;",
  "Υ": "&Upsilon;",
  "Φ": "&Phi;",
  "Χ": "&Chi;",
  "Ψ": "&Psi;",
  "Ω": "&Omega;",
  "α": "&alpha;",
  "β": "&beta;",
  "γ": "&gamma;",
  "δ": "&delta;",
  "ε": "&epsilon;",
  "ζ": "&zeta;",
  "η": "&eta;",
  "θ": "&theta;",
  "ι": "&iota;",
  "κ": "&kappa;",
  "λ": "&lambda;",
  "μ": "&mu;",
  "ν": "&nu;",
  "ξ": "&xi;",
  "ο": "&omicron;",
  "π": "&pi;",
  "ρ": "&rho;",
  "ς": "&sigmaf;",
  "σ": "&sigma;",
  "τ": "&tau;",
  "υ": "&upsilon;",
  "φ": "&phi;",
  "χ": "&chi;",
  "ψ": "&psi;",
  "ω": "&omega;",
  "ϑ": "&thetasym;",
  "ϒ": "&Upsih;",
  "ϖ": "&piv;",
  "–": "&ndash;",
  "—": "&mdash;",
  "‘": "&lsquo;",
  "’": "&rsquo;",
  "‚": "&sbquo;",
  "“": "&ldquo;",
  "”": "&rdquo;",
  "„": "&bdquo;",
  "†": "&dagger;",
  "‡": "&Dagger;",
  "•": "&bull;",
  "…": "&hellip;",
  "‰": "&permil;",
  "′": "&prime;",
  "″": "&Prime;",
  "‹": "&lsaquo;",
  "›": "&rsaquo;",
  "‾": "&oline;",
  "⁄": "&frasl;",
  "€": "&euro;",
  "ℑ": "&image;",
  "℘": "&weierp;",
  "ℜ": "&real;",
  "™": "&trade;",
  "ℵ": "&alefsym;",
  "←": "&larr;",
  "↑": "&uarr;",
  "→": "&rarr;",
  "↓": "&darr;",
  "↔": "&harr;",
  "↵": "&crarr;",
  "⇐": "&lArr;",
  "⇑": "&UArr;",
  "⇒": "&rArr;",
  "⇓": "&dArr;",
  "⇔": "&hArr;",
  "∀": "&forall;",
  "∂": "&part;",
  "∃": "&exist;",
  "∅": "&empty;",
  "∇": "&nabla;",
  "∈": "&isin;",
  "∉": "&notin;",
  "∋": "&ni;",
  "∏": "&prod;",
  "∑": "&sum;",
  "−": "&minus;",
  "∗": "&lowast;",
  "√": "&radic;",
  "∝": "&prop;",
  "∞": "&infin;",
  "∠": "&ang;",
  "∧": "&and;",
  "∨": "&or;",
  "∩": "&cap;",
  "∪": "&cup;",
  "∫": "&int;",
  "∴": "&there4;",
  "∼": "&sim;",
  "≅": "&cong;",
  "≈": "&asymp;",
  "≠": "&ne;",
  "≡": "&equiv;",
  "≤": "&le;",
  "≥": "&ge;",
  "⊂": "&sub;",
  "⊃": "&sup;",
  "⊄": "&nsub;",
  "⊆": "&sube;",
  "⊇": "&supe;",
  "⊕": "&oplus;",
  "⊗": "&otimes;",
  "⊥": "&perp;",
  "⋅": "&sdot;",
  "⌈": "&lceil;",
  "⌉": "&rceil;",
  "⌊": "&lfloor;",
  "⌋": "&rfloor;",
  "⟨": "&lang;",
  "⟩": "&rang;",
  "◊": "&loz;",
  "♠": "&spades;",
  "♣": "&clubs;",
  "♥": "&hearts;",
  "♦": "&diams;"
};
export const Cities = [
  {
    "name": "An Giang",
    "slug": "an-giang",
    "type": "tinh",
    "name_with_type": "Tỉnh An Giang",
    "code": "89",
    "area": "Miền Nam"
  },
  {
    "name": "Bà Rịa - Vũng Tàu",
    "slug": "ba-ria-vung-tau",
    "type": "tinh",
    "name_with_type": "Tỉnh Bà Rịa - Vũng Tàu",
    "code": "77",
    "area": "Miền Nam"
  },
  {
    "name": "Bắc Giang",
    "slug": "bac-giang",
    "type": "tinh",
    "name_with_type": "Tỉnh Bắc Giang",
    "code": "24",
    "area": "Miền Bắc"
  },
  {
    "name": "Bắc Kạn",
    "slug": "bac-kan",
    "type": "tinh",
    "name_with_type": "Tỉnh Bắc Kạn",
    "code": "06",
    "area": "Miền Bắc"
  },
  {
    "name": "Bạc Liêu",
    "slug": "bac-lieu",
    "type": "tinh",
    "name_with_type": "Tỉnh Bạc Liêu",
    "code": "95",
    "area": "Miền Nam"
  },
  {
    "name": "Bắc Ninh",
    "slug": "bac-ninh",
    "type": "tinh",
    "name_with_type": "Tỉnh Bắc Ninh",
    "code": "27",
    "area": "Miền Bắc"
  },
  {
    "name": "Bến Tre",
    "slug": "ben-tre",
    "type": "tinh",
    "name_with_type": "Tỉnh Bến Tre",
    "code": "83",
    "area": "Miền Nam"
  },
  {
    "name": "Bình Định",
    "slug": "binh-dinh",
    "type": "tinh",
    "name_with_type": "Tỉnh Bình Định",
    "code": "52",
    "area": "Miền Trung"
  },
  {
    "name": "Bình Dương",
    "slug": "binh-duong",
    "type": "tinh",
    "name_with_type": "Tỉnh Bình Dương",
    "code": "74",
    "area": "Miền Nam"
  },
  {
    "name": "Bình Phước",
    "slug": "binh-phuoc",
    "type": "tinh",
    "name_with_type": "Tỉnh Bình Phước",
    "code": "70",
    "area": "Miền Nam"
  },
  {
    "name": "Bình Thuận",
    "slug": "binh-thuan",
    "type": "tinh",
    "name_with_type": "Tỉnh Bình Thuận",
    "code": "60",
    "area": "Miền Trung"
  },
  {
    "name": "Cà Mau",
    "slug": "ca-mau",
    "type": "tinh",
    "name_with_type": "Tỉnh Cà Mau",
    "code": "96",
    "area": "Miền Nam"
  },
  {
    "name": "Cần Thơ",
    "slug": "can-tho",
    "type": "thanh-pho",
    "name_with_type": "Thành phố Cần Thơ",
    "code": "92",
    "area": "Miền Nam"
  },
  {
    "name": "Cao Bằng",
    "slug": "cao-bang",
    "type": "tinh",
    "name_with_type": "Tỉnh Cao Bằng",
    "code": "04",
    "area": "Miền Bắc"
  },
  {
    "name": "Đà Nẵng",
    "slug": "da-nang",
    "type": "thanh-pho",
    "name_with_type": "Thành phố Đà Nẵng",
    "code": "48",
    "area": "Miền Trung"
  },
  {
    "name": "Đăk Lăk",
    "slug": "dak-lak",
    "type": "tinh",
    "name_with_type": "Tỉnh Đắk Lắk",
    "code": "66",
    "area": "Miền Trung"
  },
  {
    "name": "Đăk Nông",
    "slug": "dak-nong",
    "type": "tinh",
    "name_with_type": "Tỉnh Đắk Nông",
    "code": "67",
    "area": "Miền Trung"
  },
  {
    "name": "Điện Biên",
    "slug": "dien-bien",
    "type": "tinh",
    "name_with_type": "Tỉnh Điện Biên",
    "code": "11",
    "area": "Miền Bắc"
  },
  {
    "name": "Đồng Nai",
    "slug": "dong-nai",
    "type": "tinh",
    "name_with_type": "Tỉnh Đồng Nai",
    "code": "75",
    "area": "Miền Nam"
  },
  {
    "name": "Đồng Tháp",
    "slug": "dong-thap",
    "type": "tinh",
    "name_with_type": "Tỉnh Đồng Tháp",
    "code": "87",
    "area": "Miền Nam"
  },
  {
    "name": "Gia Lai",
    "slug": "gia-lai",
    "type": "tinh",
    "name_with_type": "Tỉnh Gia Lai",
    "code": "64",
    "area": "Miền Trung"
  },
  {
    "name": "Hà Giang",
    "slug": "ha-giang",
    "type": "tinh",
    "name_with_type": "Tỉnh Hà Giang",
    "code": "02",
    "area": "Miền Bắc"
  },
  {
    "name": "Hà Nam",
    "slug": "ha-nam",
    "type": "tinh",
    "name_with_type": "Tỉnh Hà Nam",
    "code": "35",
    "area": "Miền Bắc"
  },
  {
    "name": "Hà Nội",
    "slug": "ha-noi",
    "type": "thanh-pho",
    "name_with_type": "Thành phố Hà Nội",
    "code": "01",
    "area": "Miền Bắc"
  },
  // {
  //   "name": "Hà Tây",
  //   "key": "ha-tay"
  // },
  {
    "name": "Hà Tĩnh",
    "slug": "ha-tinh",
    "type": "tinh",
    "name_with_type": "Tỉnh Hà Tĩnh",
    "code": "42",
    "area": "Miền Trung"
  },
  {
    "name": "Hải Dương",
    "name": "Hải Dương",
    "slug": "hai-duong",
    "type": "tinh",
    "name_with_type": "Tỉnh Hải Dương",
    "code": "30",
    "area": "Miền Bắc"
  },
  {
    "name": "Hải Phòng",
    "slug": "hai-phong",
    "type": "thanh-pho",
    "name_with_type": "Thành phố Hải Phòng",
    "code": "31",
    "area": "Miền Bắc"
  },
  {
    "name": "Hậu Giang",
    "slug": "hau-giang",
    "type": "tinh",
    "name_with_type": "Tỉnh Hậu Giang",
    "code": "93",
    "area": "Miền Nam"
  },
  {
    "name": "Hoà Bình",
    "slug": "hoa-binh",
    "type": "tinh",
    "name_with_type": "Tỉnh Hoà Bình",
    "code": "17",
    "area": "Miền Bắc"
  },
  {
    "name": "Hưng Yên",
    "slug": "hung-yen",
    "type": "tinh",
    "name_with_type": "Tỉnh Hưng Yên",
    "code": "33",
    "area": "Miền Bắc"
  },
  {
    "id": "59035f64e138233c1b5ec8b6",
    "name": "Khánh Hòa",
    "slug": "khanh-hoa",
    "type": "tinh",
    "name_with_type": "Tỉnh Khánh Hòa",
    "code": "56",
    "area": "Miền Trung"
  },
  {
    "name": "Kiên Giang",
    "slug": "kien-giang",
    "type": "tinh",
    "name_with_type": "Tỉnh Kiên Giang",
    "code": "91",
    "area": "Miền Nam"
  },
  {
    "name": "Kon Tum",
    "slug": "kon-tum",
    "type": "tinh",
    "name_with_type": "Tỉnh Kon Tum",
    "code": "62",
    "area": "Miền Trung"
  },
  {
    "id": "59035f63e138233c1b5ec6c5",
    "name": "Lai Châu",
    "slug": "lai-chau",
    "type": "tinh",
    "name_with_type": "Tỉnh Lai Châu",
    "code": "12",
    "area": "Miền Bắc"
  },
  {
    "id": "59035f5de138233c1b5eb33d",
    "name": "Lâm đồng",
    "slug": "lam-dong",
    "type": "tinh",
    "name_with_type": "Tỉnh Lâm Đồng",
    "code": "68",
    "area": "Miền Trung"
  },
  {
    "id": "59035f5ce138233c1b5eadfa",
    "name": "Lạng Sơn",
    "slug": "lang-son",
    "type": "tinh",
    "name_with_type": "Tỉnh Lạng Sơn",
    "code": "20",
    "area": "Miền Bắc"
  },
  {
    "id": "59035f59e138233c1b5ea400",
    "name": "Lào Cai",
    "slug": "lao-cai",
    "type": "tinh",
    "name_with_type": "Tỉnh Lào Cai",
    "code": "10",
    "area": "Miền Bắc"
  },
  {
    "id": "59035f66e138233c1b5ed177",
    "name": "Long An",
    "slug": "long-an",
    "type": "tinh",
    "name_with_type": "Tỉnh Long An",
    "code": "80",
    "area": "Miền Nam"
  },
  {
    "id": "59035f58e138233c1b5ea341",
    "name": "Nam Định",
    "slug": "nam-dinh",
    "type": "tinh",
    "name_with_type": "Tỉnh Nam Định",
    "code": "36",
    "area": "Miền Bắc"
  },
  {
    "id": "59035f5ce138233c1b5eb181",
    "name": "Nghệ An",
    "slug": "nghe-an",
    "type": "tinh",
    "name_with_type": "Tỉnh Nghệ An",
    "code": "40",
    "area": "Miền Trung"
  },
  {
    "id": "59035f5fe138233c1b5eba47",
    "name": "Ninh Bình",
    "slug": "ninh-binh",
    "type": "tinh",
    "name_with_type": "Tỉnh Ninh Bình",
    "code": "37",
    "area": "Miền Bắc"
  },
  {
    "id": "59035f65e138233c1b5ecd37",
    "name": "Ninh Thuận",
    "slug": "ninh-thuan",
    "type": "tinh",
    "name_with_type": "Tỉnh Ninh Thuận",
    "code": "58",
    "area": "Miền Trung"
  },
  {
    "id": "59035f64e138233c1b5ec8aa",
    "name": "Phú Thọ",
    "slug": "phu-tho",
    "type": "tinh",
    "name_with_type": "Tỉnh Phú Thọ",
    "code": "25",
    "area": "Miền Bắc"
  },
  {
    "id": "59035f5be138233c1b5ead2f",
    "name": "Phú Yên",
    "slug": "phu-yen",
    "type": "tinh",
    "name_with_type": "Tỉnh Phú Yên",
    "code": "54",
    "area": "Miền Trung"
  },
  {
    "id": "59035f5de138233c1b5eb261",
    "name": "Quảng Bình",
    "slug": "quang-binh",
    "type": "tinh",
    "name_with_type": "Tỉnh Quảng Bình",
    "code": "44",
    "area": "Miền Trung"
  },
  {
    "id": "59035f66e138233c1b5ecfce",
    "name": "Quảng Nam",
    "slug": "quang-nam",
    "type": "tinh",
    "name_with_type": "Tỉnh Quảng Nam",
    "code": "49",
    "area": "Miền Trung"
  },
  {
    "id": "59035f5ce138233c1b5eb184",
    "name": "Quảng Ngãi",
    "slug": "quang-ngai",
    "type": "tinh",
    "name_with_type": "Tỉnh Quảng Ngãi",
    "code": "51",
    "area": "Miền Trung"
  },
  {
    "id": "59035f66e138233c1b5ecec8",
    "name": "Quảng Ninh",
    "slug": "quang-ninh",
    "type": "tinh",
    "name_with_type": "Tỉnh Quảng Ninh",
    "code": "22",
    "area": "Miền Bắc"
  },
  {
    "id": "59035f5fe138233c1b5ebb3c",
    "name": "Quảng Trị",
    "slug": "quang-tri",
    "type": "tinh",
    "name_with_type": "Tỉnh Quảng Trị",
    "code": "45",
    "area": "Miền Trung"
  },
  {
    "id": "59035f65e138233c1b5ece1b",
    "name": "Sóc Trăng",
    "slug": "soc-trang",
    "type": "tinh",
    "name_with_type": "Tỉnh Sóc Trăng",
    "code": "94",
    "area": "Miền Nam"
  },
  {
    "id": "59035f59e138233c1b5ea54e",
    "name": "Sơn La",
    "slug": "son-la",
    "type": "tinh",
    "name_with_type": "Tỉnh Sơn La",
    "code": "14",
    "area": "Miền Bắc"
  },
  {
    "id": "59035f60e138233c1b5ebe68",
    "name": "Tây Ninh",
    "slug": "tay-ninh",
    "type": "tinh",
    "name_with_type": "Tỉnh Tây Ninh",
    "code": "72",
    "area": "Miền Nam"
  },
  {
    "id": "59035f64e138233c1b5ec861",
    "name": "Thái Bình",
    "slug": "thai-binh",
    "type": "tinh",
    "name_with_type": "Tỉnh Thái Bình",
    "code": "34",
    "area": "Miền Bắc"
  },
  {
    "id": "59035f58e138233c1b5ea27c",
    "name": "Thái Nguyên",
    "slug": "thai-nguyen",
    "type": "tinh",
    "name_with_type": "Tỉnh Thái Nguyên",
    "code": "19",
    "area": "Miền Bắc"
  },
  {
    "id": "59035f5be138233c1b5ead2b",
    "name": "Thanh Hóa",
    "slug": "thanh-hoa",
    "type": "tinh",
    "name_with_type": "Tỉnh Thanh Hóa",
    "code": "38",
    "area": "Miền Trung"
  },
  {
    "id": "59035f65e138233c1b5ecdd7",
    "name": "Thừa Thiên Huế",
    "slug": "thua-thien-hue",
    "type": "tinh",
    "name_with_type": "Tỉnh Thừa Thiên Huế",
    "code": "46",
    "area": "Miền Trung"
  },
  {
    "id": "59035f5be138233c1b5eac95",
    "name": "Tiền Giang",
    "slug": "tien-giang",
    "type": "tinh",
    "name_with_type": "Tỉnh Tiền Giang",
    "code": "82",
    "area": "Miền Nam"
  },
  {
    "id": "59035f5ee138233c1b5eb7aa",
    "name": "TP. Hồ Chí Minh",
    "slug": "ho-chi-minh",
    "type": "thanh-pho",
    "name_with_type": "Thành phố Hồ Chí Minh",
    "code": "79",
    "area": "Miền Nam"
  },
  {
    "id": "59035f58e138233c1b5ea289",
    "name": "Trà Vinh",
    "slug": "tra-vinh",
    "type": "tinh",
    "name_with_type": "Tỉnh Trà Vinh",
    "code": "84",
  },
  {
    "id": "59035f5ae138233c1b5ea79e",
    "name": "Tuyên Quang",
    "slug": "tuyen-quang",
    "type": "tinh",
    "name_with_type": "Tỉnh Tuyên Quang",
    "code": "08",
    "area": "Miền Bắc"
  },
  {
    "id": "59035f59e138233c1b5ea57b",
    "name": "Vĩnh Long",
    "slug": "vinh-long",
    "type": "tinh",
    "name_with_type": "Tỉnh Vĩnh Long",
    "code": "86",
    "area": "Miền Nam"
  },
  {
    "id": "59035f5ee138233c1b5eb5e2",
    "name": "Vĩnh Phúc",
    "slug": "vinh-phuc",
    "type": "tinh",
    "name_with_type": "Tỉnh Vĩnh Phúc",
    "code": "26",
    "area": "Miền Bắc"
  },
  {
    "id": "59035f5ae138233c1b5ea7bd",
    "name": "Yên Bái",
    "slug": "yen-bai",
    "type": "tinh",
    "name_with_type": "Tỉnh Yên Bái",
    "code": "15",
    "area": "Miền Bắc"
  }
];