

//
export const SET_TAB = 'SET_TAB';
export const COUNT_NOTIFY = 'COUNT_NOTIFY';
export const COUNTRIES_SUCCESS = 'COUNTRIES_SUCCESS';
export const BANKS_SUCCESS = 'BANKS_SUCCESS';
export const CITIES_SUCCESS = 'CITIES_SUCCESS';
//ORDER_CANCEL_SUCCESS
export const ORDER_CANCEL_SUCCESS = 'ORDER_CANCEL_SUCCESS';
export const GET_MONEY_SUCCESS = 'GET_MONEY_SUCCESS';

// UPDATE_REQUEST
export const UPDATE_REQUEST = 'UPDATE_REQUEST';

//SET_LOGIN
export const SET_LOGIN = 'SET_LOGIN';
//TAKE_MONEY_SUCCESS
export const TAKE_MONEY_REQUEST = 'TAKE_MONEY_REQUEST';
export const TAKE_MONEY_SUCCESS = 'TAKE_MONEY_SUCCESS';
export const TAKE_MONEY_FAIL = 'TAKE_MONEY_FAIL';

//SET_ARR_NOTI
export const SET_ARR_NOTI = 'SET_ARR_NOTI';
//contact
export const SAVE_CONTACT_REQUEST = 'SAVE_CONTACT_REQUEST';
export const SAVE_CONTACT_SUCCESS = 'SAVE_CONTACT_SUCCESS';

//
export const GET_SHIP_SUCCESS = 'GET_SHIP_SUCCESS';
export const CART_VERIFY_SUCCESS = 'CART_VERIFY_SUCCESS';
export const DELETE_ADDRESS_SUCCESS = 'DELETE_ADDRESS_SUCCESS';
//add address
export const ADD_ADDRESS_REQUEST = 'ADD_ADDRESS_REQUEST';
export const ADD_ADDRESS_SUCCESS = 'ADD_ADDRESS_SUCCESS';
export const ADD_ADDRESS_FAIL = 'ADD_ADDRESS_FAIL';
//edit
export const EDIT_ADDRESS_SUCCESS = 'EDIT_ADDRESS_SUCCESS';
//load address
export const CART_ADDRESS_REQUEST = 'CART_ADDRESS_REQUEST';
export const CART_ADDRESS_SUCCESS = 'CART_ADDRESS_SUCCESS';
export const CART_ADDRESS_FAIL = 'CART_ADDRESS_FAIL';
//create order
export const CREATE_ORDER = 'CREATE_ORDER';

//orderDetail
export const ORDER_DETAIL_REQUEST = 'ORDER_DETAIL_REQUEST';
export const ORDER_DETAIL_SUCCESS = 'ORDER_DETAIL_SUCCESS';

//notify
export const NOTIFY_DETAIL_SUCCESS = 'NOTIFY_DETAIL_SUCCESS';
export const NOTIFY_REQUEST = 'NOTIFY_REQUEST';
export const NOTIFY_SUCCESS = 'NOTIFY_SUCCESS';
export const NOTIFY_FAIL = 'NOTIFY_FAIL';

//about
export const ABOUT_REQUEST = 'ABOUT_REQUEST';
export const ABOUT_SUCCESS = 'ABOUT_SUCCESS';
//updatge address
export const UPDATE_ADDRESS_REQUEST = 'UPDATE_ADDRESS_REQUEST';
export const UPDATE_ADDRESS_SUCCESS = 'UPDATE_ADDRESS_SUCCESS';
export const UPDATE_ADDRESS_FAIL = 'UPDATE_ADDRESS_FAIL';

//editProfile
export const EDIT_PROFILE_REQUEST = 'EDIT_PROFILE_REQUEST';
export const EDIT_PROFILE_SUCCESS = 'EDIT_PROFILE_SUCCESS';
export const EDIT_PROFILE_FAIL = 'EDIT_PROFILE_FAIL';

//profile order
export const ORDER_REQUEST = 'ORDER_REQUEST';
export const ORDER_SUCCESS = 'ORDER_SUCCESS';
export const ORDER_FAIL = 'ORDER_FAIL';

//QA
export const QA_REQUEST = 'QA_REQUEST';
export const QA_SUCCESS = 'QA_SUCCESS';
export const QA_FAIL = 'QA_FAIL';

//send QA
export const SEND_QA_SUCCESS = 'SEND_QA_SUCCESS';

///category detail
export const PRODUCT_CATEGORY_REQUEST = 'PRODUCT_CATEGORY_REQUEST';
export const PRODUCT_CATEGORY_SUCCESS = 'PRODUCT_CATEGORY_SUCCESS';
export const PRODUCT_CATEGORY_FAIL = 'PRODUCT_CATEGORY_FAIL';

///product detail
export const PRODUCT_DETAIL_REQUEST = 'PRODUCT_DETAIL_REQUEST';
export const PRODUCT_DETAIL_SUCCESS = 'PRODUCT_DETAIL_SUCCESS';
export const PRODUCT_DETAIL_FAIL = 'PRODUCT_DETAIL_FAIL';

//search
export const SEARCH_REQUEST = 'SEARCH_REQUEST';
export const SEARCH_SUCCESS = 'SEARCH_SUCCESS';
export const SEARCH_FAIL = 'SEARCH_FAIL';

//profile
export const PROFILE_SUCCESS ='PROFILE_SUCCESS';

//load home more detail
export const HOME_DETAIL_REQUEST = 'HOME_DETAIL_REQUEST';
export const HOME_DETAIL_SUCCESS = 'HOME_DETAIL_SUCCESS';
export const HOME_DETAIL_FAIL = 'HOME_DETAIL_FAIL';
//load home
export const HOME_REQUEST = 'HOME_REQUEST';
export const HOME_SUCCESS = 'HOME_SUCCESS';
export const HOME_FAIL = 'HOME_FAIL';

export const LOGIN_REQUEST = 'LOGIN_REQUEST';
export const LOGIN_SUCC = 'LOGIN_SUCC';
export const LOGIN_FAIL = 'LOGIN_FAIL';