# Uncomment the next line to define a global platform for your project
platform :ios, '9.0'

target 'ladin' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for ladin

  rn_path = '../node_modules/react-native'
  pod 'yoga', path: "#{rn_path}/ReactCommon/yoga/yoga.podspec"
  pod 'React', path: rn_path, subspecs: [
    'Core',
    'RCTActionSheet',
    'RCTAnimation',
    'RCTGeolocation',
    'RCTImage',
    'RCTLinkingIOS',
    'RCTNetwork',
    'RCTSettings',
    'RCTText',
    'RCTVibration',
    'RCTWebSocket'
  ]

  pod 'RNImageCropPicker', :path =>  '../node_modules/react-native-image-crop-picker'

  pod 'Firebase/Core', '~> 4.13.0'
  pod 'Firebase/Messaging','~> 4.13.0'
  pod 'rn-fetch-blob', :path => '../node_modules/rn-fetch-blob'
 	pod 'react-native-splash-screen', :path => '../node_modules/react-native-splash-screen'
  target 'ladinTests' do
    inherit! :search_paths
    # Pods for testing
  end

end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    if target.name == "React"
      target.remove_from_project
    end
  end
end

target 'ladin-tvOS' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for ladin-tvOS

  target 'ladin-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
